name: mobile_framwork
description: Egp User App
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_launcher_icons: ^0.7.2+1
  http: ^0.12.0+2
  shared_preferences: ^0.5.3+1
  imei_plugin: ^1.0.0
  path_provider: ^1.1.2
  dio: ^2.1.13
  webview_flutter: ^0.3.10+3
  image_picker: ^0.6.1
  geolocator: ^5.1.1+1
  location: ^2.3.5
  flutter_luban: ^0.1.7+1
  latlong: ^0.6.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  image_path: "icon/icon.png"
  android: true
  ios: true
flutter:
  uses-material-design: true
  assets:
    - under_con.png
    - egp_logo.png
    - assets/images/
